version: '2'
services:
    eo-app:
        image: eo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://eo-postgresql:5432/eo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    eo-postgresql:
        extends:
            file: postgresql.yml
            service: eo-postgresql
